### ISSUE TITLE
Remove grunt dependency 

### ISSUE THREAD

**Issue by colestrode** [SparkPost/node-sparkpost#105]
Looking at the grunt file, there's nothing in there that can't be accomplished with NPM scripts: jshint, mocha, and coveralls all have command line tools, and `npm version` does basically the same thing as `grunt bump`.

I say we remove grunt in favor of npm scripts. That will remove several dev deps that aren't really providing any value.

Since we already define test and ci commands in package.json, this would be a transparent change to users and ci integration.

**Comment by aydrian** [comment]
Here is a list of what grunt is currently doing
- [ ] JSLint
- [ ] Version bumping
- [ ] Running Tests
- [ ] Running Coverage Report
- [ ] Coveralls Task

**Comment by aydrian** [comment]
Closed by #160
