### ISSUE TITLE
Improve documentation.

### ISSUE THREAD

**Issue by aydrian** [SparkPost/node-sparkpost#113]
Add links to API documentation or make it somehow easier to see properties

**Comment by JimTheMan** [comment]
What do you mean by "see properties"? I set up my domain in sparkpost, created an api key, and now i just want to send a "hello world" email with your api. Can you put _that_ in the readme? 

This other github does a really nice job of it. We could use their readme as a model for our own: [(https://github.com/amail/alphamail-nodejs-client)]

**Comment by aydrian** [comment]
Thank you for your feedback. I'm the maintainer of this library and I was quickly adding feedback from our [slack community](http://slack.sparkpost.com). I'm going to look at the other library and see what I can do to improve our docs.

**Comment by aydrian** [comment]
Documentation was updated as we refactored each resource.
