### ISSUE TITLE
How To Send A Basic Email?

### ISSUE THREAD

**Issue by JimTheMan** [SparkPost/node-sparkpost#114]
Hi. Your first readme page should have the complete code to send a basic email. It should looks something like this one: https://github.com/amail/alphamail-nodejs-client

**Comment by bizob2828** [comment]
hmm yea I do agree we should probably feature this on the first page of the read me. Anyways it's here https://github.com/SparkPost/node-sparkpost/blob/master/docs/resources/transmissions.md

**Comment by aydrian** [comment]
Closed by #115
