### ISSUE TITLE
Integrate with TravisCI

### ISSUE THREAD

**Issue by bdeanindy** [SparkPost/node-sparkpost#12]
Need to integrate with Travis CI so we have automatic testing in place.

**Comment by bdeanindy** [comment]
@richleland and @bizob2828 This should be enough to make sure that it works (you can see it running against my fork here: https://travis-ci.org/bdeanindy/node-sparkpost

**Comment by bdeanindy** [comment]
I am also going to submit the PR for the docs which indicated we should be using CI (thus the driver for this). We can build out the tests more later.

**Comment by richleland** [comment]
Travis is set up - anything else to do here?

**Comment by jmartin4563** [comment]
Closed by https://github.com/SparkPost/node-sparkpost/pull/13, if there is more work to do, then please reopen.
