### ISSUE TITLE
Type Error when response body is undefined

### ISSUE THREAD

**Issue by mstdokumaci** [SparkPost/node-sparkpost#127]
For Sparkpost v1.1.0, we got this error on our production server:
`TypeError: Cannot read property 'errors' of undefined at Request._callback (/.../node_modules/sparkpost/lib/sparkpost.js:94:24)`

Which hits this line `err.errors = body.errors;`

Which means body might be undefined at the response of request.

Fixed by PR: #126

**Comment by ewandennis** [comment]
Do you have any idea of the HTTP response that triggered this?

**Comment by mstdokumaci** [comment]
Unfortunately we don't have it logged, node-sparkpost threw an exception, that's what we got.

**Comment by ewandennis** [comment]
Ok thanks.

**Comment by ewandennis** [comment]
Do you happen to know which endpoint you were calling when this occurred?  `transmissions.send()` maybe?  Even if you can just narrow it down to the list of node-sparkpost function calls you make, that'd be very useful.

**Comment by mstdokumaci** [comment]
It happens while sending e-mail by `sparkpost.transmissions.send(...)`

**Comment by aydrian** [comment]
closed by #126
