### ISSUE TITLE
inboundDomains.create() does not work as per docs

### ISSUE THREAD

**Issue by orval** [SparkPost/node-sparkpost#133]
The documentation is as follows:

- *create(domain, callback)*
  Create a new inbound domain
  - `domain` - the name of the domain you want to create **required**
  - `callback` - see all function

Setting `domain` to a domain name does not work. It gives the error `Missing required field: (domain) is required`.

A workaround is to use an object with a domain property like this: `{ domain: myDomain }`

**Comment by jgzamora** [comment]
Is this outdated? I ran the create_inbound domain example, which just passes in a domain, and it worked.
<img width="512" alt="screen shot 2016-05-11 at 11 52 27 am" src="https://cloud.githubusercontent.com/assets/3607539/15187448/25370bf2-176f-11e6-85e8-66961954da5d.png">

**Comment by orval** [comment]
Fixed in https://github.com/SparkPost/node-sparkpost/pull/134
