### ISSUE TITLE
Suppression List upsert_bulk example not working.

### ISSUE THREAD

**Issue by sibrus** [SparkPost/node-sparkpost#140]
### System Info
OS: Ubuntu Precise x64
NodeJS ver: v0.12.7
node-sparkpost version: 1.3.2 from npm

### Issue Description

When trying to run the following sample code (with my own API key of course): https://github.com/SparkPost/node-sparkpost/blob/1.3.2/examples/suppressionList/upsert_bulk.js

The result is the following:
```
{ [SparkPostError: Bad Request]
  name: 'SparkPostError',
  errors: [ { message: 'PUT body must contain an array of recipients' } ],
  statusCode: 400 }
```

**Comment by aydrian** [comment]
This has been released as v1.3.4 and is available via npm.
