### ISSUE TITLE
Update to a newer version of request

### ISSUE THREAD

**Issue by artlogic** [SparkPost/node-sparkpost#141]
As of today, [NSP](https://nodesecurity.io/tools) is warning me of a vulnerability found in the version of hawk depended upon by the older version of request (2.42.0) you depend upon. Please upgrade request to a more recent version, if possible.

If this is simply bumping a version and running tests, I'd be happy to submit a pull request.

**Comment by colestrode** [comment]
Thanks for the heads up @artlogic. A PR would be great 😄

**Comment by artlogic** [comment]
@colestrode submitted - let me know if you need me to do anything else.

**Comment by aydrian** [comment]
This has been published to npm as v1.3.3. Thank you.
