### ISSUE TITLE
Add sandbox option to transmissions

### ISSUE THREAD

**Issue by jmartin4563** [SparkPost/node-sparkpost#15]
The transmissions api has added a new option to the payload of a request; a sandbox option delineating whether or not a given transmission is using the sandbox domain or not.

The option itself is a boolean, and in the API payload, it's part of the options object (in with open/click tracking). The key the API accepts is `sandbox`

`model.options.sandbox` must be boolean

**Comment by bizob2828** [comment]
not a bug @bdeanindy as this is a new option that will be implemented

**Comment by bizob2828** [comment]
@jmartin4563 can you take a look at this sometime? if it is good just merge

**Comment by jmartin4563** [comment]
Closed by https://github.com/SparkPost/node-sparkpost/pull/18
