### ISSUE TITLE
CC and BCC

### ISSUE THREAD

**Issue by Bharathvijay** [SparkPost/node-sparkpost#151]
The CC and BCC feature doesn't seems to be working . Could someone please figure out my issue. The below code snippet would make you understand what I am trying to do.

```
var SPARKPOST_KEY = "KEY"
var sparkpost = require('sparkpost');
var sparkclient = new sparkpost(SPARKPOST_KEY);

var req_opts = {
	transmissionBody : {
		content: {
			template_id: 'order-confirmation',
			from: 'support@domain.com',
      		subject: 'Order confirmation',
      		headers: {
      			"CC": "<anon2@domain1.com>"
      		}
		},
		substitution_data: {
			"customer": "Mike",
			"order": 123532
		},
		recipients: [
      		{address: {email:'anon1@domain1.com'}},
      		{address: {email: 'anon2@domain1.com'}}
    	],
    	"return_path": "support@domain.com",
	}
};

sparkclient.transmissions.send(req_opts, function(err, res){
	if(err){
		console.log("ERROR");
		console.log(err)
	}else {
		console.log(res.body);
		console.log("Mail has been successfully sent");
	}
});
```

**Comment by ewandennis** [comment]
Hi.  It looks like you are mixing a stored template and inline template fields.  You can use only a stored template **or** an inline template in any single transmission.

In your snippet above, you could remove the `template-id` field and add `html` and `text` content to your transmission call:

```javascript
{
  transmissionBody: {
    content: {
            from: 'support@domain.com',
            subject: 'Order confirmation',
            headers: {
                "CC": "<anon2@domain1.com>"
            },
            html: 'html message',
            text: 'plain text message'
    }
// ...
}
```

Alternately, you could put a substitution variable into your template for the CC header using the [templates API endpoint](https://developers.sparkpost.com/api/templates#templates-update-put) and set them in your tranmission call:

{
  transmissionBody: {
    content: {
      template_id: 'order-confirmation'
    },
    substitution_data: {
        "CC": "anon2@domain1.com"
    }
// ...
}

**Comment by Bharathvijay** [comment]
Where do I set the CC header in the template. Can you please help me out with that ?

**Comment by ewandennis** [comment]
Closing this in favour of [your StackOverflow post here](http://stackoverflow.com/questions/38762051/sending-cc-and-bcc-in-substitution-data-when-calling-node-sparkpost-api).
