### ISSUE TITLE
You do not support camel case...?  Why?

### ISSUE THREAD

**Issue by bradennapier** [SparkPost/node-sparkpost#152]
I'm fairly confused as-to why camel case is not supported by this library?  It's extremely annoying having to manually re-factor every single key that I use just because your javascript library for some reason ignores them...........

I am using 1.3.7 (latest in npm)

{{order.discountType}} will always == ""

works 100% fine from preview but the items are just missing completely from my actual emails which is even more annoying :(

**Comment by aydrian** [comment]
Substitution data should be added using `substitution_data` and not `substitionData`. This was causing an issue with our `toApiFormat` function. I will go through and make sure all the documentation and examples are using the correct format.

**Comment by aydrian** [comment]
I've searched the repo and only found one use of `substitutionData`. It has been updated.
