### ISSUE TITLE
Create a base resource object

### ISSUE THREAD

**Issue by bizob2828** [SparkPost/node-sparkpost#16]
When we shipped the sdk there was only one API.  We had a pull request for sending-domains and a lot of duplicated code existed.  

Task:
 Build a base resource that takes care of all the common pieces like a fetch, create, building url

**Comment by aydrian** [comment]
Here is a first stab to kick off a discussion. Let me know your thoughts.
https://github.com/aydrian/node-sparkpost/commit/0fd132999f48b10c7170a673f346b412c6f01397

**Comment by aydrian** [comment]
Base Resource Object should have following methods:
sparkRequest: wrapped request call
get: find one
list: find collection
create: adds item
update: updates item
delete: delete item
