### ISSUE TITLE
Migrate docs to be in github wiki

### ISSUE THREAD

**Issue by bizob2828** [SparkPost/node-sparkpost#17]
Having our docs in README gets very cluttered. It would be good to create a github wiki and have pages for each resource within the SDK.  Also perhaps a getting started/landing page

**Comment by bdeanindy** [comment]
We're opting for referencing relative markdown files in the repository for now, but we'll implement this in a later rev.

**Comment by aydrian** [comment]
I believe what we want to do is use Github Pages. This may be what you meant. This would give us a site at sparkpost.github.io/node-sparkpost.

**Comment by bdeanindy** [comment]
Yes, that should be just fine if that accomplishes the goal of making the in-repo docs easier to digest.

**Comment by aydrian** [comment]
Using markdown links is now the standard method for all client libs. Closing Issue.
