### ISSUE TITLE
error in lib/sparkpost.js

### ISSUE THREAD

**Issue by urgavega** [SparkPost/node-sparkpost#179]
Hello.
I found an error in lib/sparkpost.js at request function on 104 line.

There is `err.errors = body.errors;` 
but request function return body as string 
http://clip2net.com/s/3CIbLbk

So script doesn't work correctly in case error. It shows 'undefined'

It needs `err.errors = (JSON.parse(body)).errors;`
      insdead of `err.errors = body.errors;`
      on line 104

Can you check it and fix it, please?

**Comment by aydrian** [comment]
This is a known issue and is being fixed in 2.0.0. You can check our our [WIP branch](https://github.com/SparkPost/node-sparkpost/tree/wip-2.0.0). We are putting on some finishing touches and hope to have it released soon.
