### ISSUE TITLE
Return full body not just results for GET requests

### ISSUE THREAD

**Issue by colestrode** [SparkPost/node-sparkpost#185]
For GET requests, return only the `results` key, but for message-events this means that users will not have access to the `links` or `totalCount` keys. This makes pagination very difficult. I think we should just pass the body straight through. This is also in line with keeping the client as a thin wrapper on the API.

**Comment by aydrian** [comment]
I'm fine with this change. I think I borrowed it from one of our other client libraries.

**Comment by aydrian** [comment]
Closed by #186
