### ISSUE TITLE
Provide export as .csv feature for GET responses

### ISSUE THREAD

**Issue by bdeanindy** [SparkPost/node-sparkpost#19]
People may want to use the SDK to offer an easy "download as .csv" format for responses.

We should make that simple and bind it to the following SparkPost API services:

- Templates
- Recipient Lists
- Suppression Lists
- Sending Domains

**Comment by aydrian** [comment]
This may simplify efforts: https://github.com/zeMirco/json2csv

**Comment by colestrode** [comment]
Like @aydrian said, there are utilities to convert JSON to CSV. I think we should return JSON and let users process it how they want. I'm closing until we hear from someone in the community that this would be a useful feature.
