### ISSUE TITLE
Add information about the breaking changes to the changelog (or somewhere)

### ISSUE THREAD

**Issue by danieljuhl** [SparkPost/node-sparkpost#191]
I fully understand that there is breaking changes in the latest version (v2.0.0) - but I can't find any place, where the breaking changes is outlined.

I have found some of them in the changelog (stuff that has been removed), but I don't know if that everything.

Please, add some information about ALL breaking changes, so we (clients/developers using the API) doesn't have to go through all the code.

**Comment by aydrian** [comment]
Apologies. This is coming.

**Comment by danieljuhl** [comment]
@aydrian any news? This is blocking safe upgrades.

**Comment by aydrian** [comment]
@danieljuhl I'm targeting end of my day tomorrow.

Out of curiosity, would you mind telling me which parts of the client library beyond transmissions you are using?

**Comment by danieljuhl** [comment]
Message events and suppression list

**Comment by aydrian** [comment]
Please have a look at PR #192. I have refactored the changelog. Between that and the examples/resource docs, you should be good.
At a high level, the Message Events wrapper did not change. You shouldn't see a problem.
For the Suppression List wrapper the method names were standardized:
`search` -> `list`
`checkStatus` -> `get`
`removeStatus` -> `delete`
