### ISSUE TITLE
[Question] How to send multiple emails with different content

### ISSUE THREAD

**Issue by weblancaster** [SparkPost/node-sparkpost#196]
I have looked the API doc and went through the help questions on the website and lastly I tried looking the other language support to see if I could find something but nothing.

Basically I have a loop where for each element in the array I send an email to a different email address and different html content.

The problem is that I was the only one (the first in the array) that received the email but the logs (and Sparkpost dashboard) shows that I have sent to the exact number of elements I have in the array.

Any thoughts on that? thanks in advance.

```javascript
sender.transmissions.send({
    options: {
      open_tracking: true,
      click_tracking: true
    },
    content: {
      from: 'blabla@blabla.com',
      subject: `Hey! ${user.name} blablablabla`,
      reply_to: 'blabla@blabla.com',
      html: digestTemplate(user) // generate customized template
    },
    recipients: [
      {
        address: `${user.email}`,
        name: `${user.name}`
      }
    ]
  })
    .then(data => {
     // all emails succeed but only the first received
      console.log(`Email sent to ${user.email}!`);
      console.log(data);
    })
    .catch(err => {
      console.log('Something went wrong');
      console.log(err);
    });
}
```

**Comment by aydrian** [comment]
All the emails are showing up as injected? I would also recommend you do this using our templates, either inline or as a saved template. That would push the processing of the messages to our side and it would create a single job. You can find additional information in our [substitution reference docs](https://developers.sparkpost.com/api/substitutions-reference).

**Comment by weblancaster** [comment]
@aydrian thanks for your reply. Yes all displaying as injected.

Next I'm going to try to use the saved template option with substitution reference.

I just found odd that only the first person actually received the email even though the dashboard is displaying that all did. Is there any technical reason for that?

**Comment by aydrian** [comment]
If you are still having issues with people receiving messages then I would suggest you open a [support ticket](https://support.sparkpost.com/customer/portal/emails/new). Thanks.
