### ISSUE TITLE
Test the callback implementation

### ISSUE THREAD

**Issue by jasonrhodes** [SparkPost/node-sparkpost#201]
Would be good to use some sort of `sinon.stub().yields()` system and pass in callback stubs in all of the tests to make sure they're called, so we know we don't break the callback functionality if we make changes.

**Comment by rajumsys** [comment]
@jasonrhodes I was looking to create a PR for this but I see it's been already covered. https://github.com/SparkPost/node-sparkpost/blob/master/test/spec/transmissions.spec.js#L105

Has same for other methods. It's not using `yields` but still testing same thing; whether callback is called. 

Is there something else you were referring to?

**Comment by rajumsys** [comment]
As per our (offline) discussion, this part is covered, hence closing it.
