### ISSUE TITLE
Sending a scheduled email

### ISSUE THREAD

**Issue by jsgandalf** [SparkPost/node-sparkpost#205]
Quick Question,

Problem: I have tried numerous times to set a start_time to be scheduled in advance. However the result happens over and over, the email is always delivered immediately. This is not the result I'd expect, whats wrong with my code? :/

I've read the following documentation which allows you to send scheduled Emails:

https://developers.sparkpost.com/api/transmissions.html#header-options-attributes

Today is 2017-02-03, I'm setting 8 days in advance: 2017-02-11T08:00:00-04:00

```
function email(toEmail, campaignId, templateId, startTime){
  var transmission = {
    campaign_id: campaignId,
    content: {
      template_id: templateId
    },
    recipients: [{address: toEmail}]
  }
  , options = {
    start_time: '2017-02-11T08:00:00-04:00',
    num_rcpt_errors: 3
  };
  return sparky.transmissions.send(transmission, options);
}
```

**Comment by aydrian** [comment]
Ah. I see what the problem is. There is an options for the [`transmission` object](https://developers.sparkpost.com/api/transmissions.html#header-transmission-attributes). The `start_time` goes in there.
Try this:
```javascript
function email(toEmail, campaignId, templateId, startTime){
  var transmission = {
    campaign_id: campaignId,
    content: {
      template_id: templateId
    },
    recipients: [{address: toEmail}]
    , options = {
      start_time: '2017-02-11T08:00:00-04:00'
    }
  }
  , options = {
    num_rcpt_errors: 3
  };
  return sparky.transmissions.send(transmission, options);
}
```

**Comment by jsgandalf** [comment]
@aydrian Thank you Thank you Thank you Thank you Thank you x10000!!!!!!!!!!
