### ISSUE TITLE
Inlining CSS

### ISSUE THREAD

**Issue by retorquere** [SparkPost/node-sparkpost#206]
Should adding `options: { inline_css: true },` to the options object be sufficient to inline css? Right now I'm not seeing any inlined CSS; pre-processing the html with https://www.npmjs.com/package/inline-css does the job but I thought SparkPost should be able to do this on my behalf.

**Comment by aydrian** [comment]
The option is part of the `transmission` object which is the first parameter to the `send()` function. It won't work if you include it in the optional second parameter.  You can see the option here which is a sibling to the recipients attribute: https://developers.sparkpost.com/api/transmissions.html#header-options-attributes. The value should be passed directly to the API. If you are still seeing issues, it'd be best to open a [support ticket](https://support.sparkpost.com/customer/portal/emails/new).

**Comment by retorquere** [comment]
Super, works.
