### ISSUE TITLE
content.inline_images

### ISSUE THREAD

**Issue by monstrfolk** [SparkPost/node-sparkpost#207]
Are inline_images supported? 

I have tried using them and can not get the option to work.

[https://developers.sparkpost.com/api/transmissions.html#header-inline-image-attributes](https://developers.sparkpost.com/api/transmissions.html#header-inline-image-attributes)

**Comment by aydrian** [comment]
The library should pass thru all the api parameters directly. Could you give me a sample of the code you are using?

**Comment by aydrian** [comment]
I've added an example here: https://github.com/SparkPost/node-sparkpost/blob/master/examples/transmissions/send_inline_image.js

**Comment by monstrfolk** [comment]
Thanks for that. 

I noticed that inline_images are not supported with predefined templates. Do you know if that feature is going to be supported by SparkPost?

**Comment by aydrian** [comment]
I have checked and it looks like we don't have any plans to support inline images in stored templates. A work around would be to create a template and then use the template endpoint to pull the code and inline it at time of send and include the `inline_images` at that time.

**Comment by monstrfolk** [comment]
Thanks.

One more question...Could post another example how to retrieve a template endpoint or show me where to find the documentation for retrieving an endpoint?

**Comment by aydrian** [comment]
You can find our template examples [here](https://github.com/SparkPost/node-sparkpost/tree/master/examples/templates). This [example](https://github.com/SparkPost/node-sparkpost/blob/master/examples/templates/get.js) shows you how to retrieve a stored template.

**Comment by aydrian** [comment]
If this has answered your question, could you please close the issue? You can always come chat with us at [slack.sparkpost.com](http://slack.sparkpost.com). We have a #node channel.
