### ISSUE TITLE
email goes to spam with the verified domain

### ISSUE THREAD

**Issue by codalprashant** [SparkPost/node-sparkpost#211]
Sending email from sparkpost from 'no-reply@xyz.com' goes to spam folder. How can i overcome such issue ?

**Comment by richleland** [comment]
Hi @codalprashant - you'll want to reach out to our support crew by [submitting a ticket](https://www.sparkpost.com/submit-a-ticket/). This issue tracker is for issues with the client library itself. Thanks for joining SparkPost!
