### ISSUE TITLE
Set the sandbox from address

### ISSUE THREAD

**Issue by davidfloegel** [SparkPost/node-sparkpost#218]
Hi, 

great library!

I'm trying to use the sandbox but I've exceeded my lifetime limit of 5 emails. I'm trying to override the from email address to prevent that from happening with:
```javascript
{
   content: {
     from: {
       email: 'myemailaddress'
     }
   }
}
```

But it doesn't seem to work!
Any ideas?

Thanks
David

**Comment by aydrian** [comment]
Hey David. Thanks. The from email needs to be from one of your verified sending domains. Also make sure you remove the
```javascript
options: {
  sandbox: true
}
```
from the transmission.

**Comment by davidfloegel** [comment]
Hey aydrian! Thanks for the quick response!

Interesting, I've verified my domain through Account -> Sending Domains and removed the `options`.

So my verified domain is `mydomain.com` and my from email address is `hello@mydomain.com`.
However I'm now recieving:
```
{ 
  message: 'Message generation rejected',
  description: 'Sending domain sandbox option mismatch',
  code: '1902' 
}
```

The sandbox option should be off now so it should technically just send?

Thanks!

**Comment by aydrian** [comment]
Yes. That error means that you don't have both the sandbox address and the sandbox option set. It sounds like you just didn't remove the option. Let me know if it went through.

**Comment by davidfloegel** [comment]
Hm, no luck I'm afraid..

This is my configuration:
```
this.client.transmissions.send({
  content: {
    from: 'hello@mydomain.com',
    template_id: 'welcome-email'
  },
  recipients: [...]
})
```

Still getting the same error though.  Am I missing something really obvious? 😅

**Comment by aydrian** [comment]
Oh. You're using a template. You set the from address in the template. You don't need to put it in the content. Make sure your from address is set in your template and remove it from your transmission code. Give that a shot.

**Comment by davidfloegel** [comment]
Aah ok that worked!
I believe I had to re-publish my template though after changing the address which was a bit unintuitive.

Anyways, thanks for the quick help! :)
