### ISSUE TITLE
Send different email content to different users friends list

### ISSUE THREAD

**Issue by loveforweb** [SparkPost/node-sparkpost#219]
Hi, Im trying to figure out how to send multiple transmissions in one request (an array of objects), is this possible?

Basically, I have a list of users, who each have a list of friends (recipients). For each users, I need the ability to send out an email to their friends, each user can have different email content from other users. I also need a way to pass the relevant users names to each transmission object as it will be included in the email content

So as a rough (incomplete) example, could i do the following: 

```
transmission = [{
        recipients: [
            // {recipients objects}
        ],
        content: {
           from: {
                name: 'John Flintstone',
                email: 'hello@flintstone.com'
            },
            subject: 'Howdy!',
            reply_to: 'My Information <hello@flintstone.com>',
            text: 'Hi {{address.name}} Some other information\n {{sender}}',
            html: '<p>Hi {{address.name}} Some other information<p>{{sender}}</p>'
        }
}, {
        recipients: [
            // {recipients objects}
        ],
        content: {
           from: {
                name: 'Fred Flintstone',
                email: 'hello@flintstone.com'
            },
            subject: 'The Subject!',
            reply_to: 'My Campaign <hello@flintstone.com>',
            text: 'Hi {{address.name}} Some other information\n {{sender}}',
            html: '<p>Hi {{address.name}} Some other information<p>{{sender}}</p>'
        }
}]
```

Thanks in advance

**Comment by aydrian** [comment]
It looks like you are on the right track. You just need one transmission and content with `substitution_data`. You can provide `substitution_data` at the [recipient](https://developers.sparkpost.com/api/recipient-lists.html#header-recipient-attributes) level. This would allow you to set info like their name and info about the friend sending them the message. This substitution data gets merged into the top level substitution data. So it would look more like the following:
```javascript
let transmission = {
  recipients: [
    {
      address: {
        email: 'mr_slate@bedrock.com',
        name: 'Mr. Slate'
      },
      substitution_data: {
        sender: {
          name: 'Fred Flintstone'
        }
      }
    }, {
      address: {
        email: 'bambam@bedrock.com',
        name: 'Bambam Rubble'
      },
      substitution_data: {
        sender: {
          name: 'Wilma Flintstone'
        }
      }
    }
  ],
  content: {
    from: {
      name: '{{ sender.name }}',
      email: 'hello@flintstone.com'
    },
    subject: 'Howdy!',
    reply_to: 'My Information <hello@flintstone.com>',
    text: 'Hi {{ address.name }} Some other information\n {{ sender.name }}',
    html: '<p>Hi {{ address.name }} Some other information<p>{{ sender.name }}</p>'
  }
}
```

I just tried this with real email addresses and it worked. Please let me know if you have any additional questions.

**Comment by loveforweb** [comment]
that looks great, but is there a way where the content.subject/text/html can be different for each User? At the moment, each User is sending the same email content to their recipients, Fred Flintstone may not want to send the same content as Wilma Flintstone

**Comment by aydrian** [comment]
You would have to figure out a way to pass the content into the template from substitution_data. It might be worth it to just send multiple transmission posts.

**Comment by loveforweb** [comment]
Thats cool, I'll have a play around and see what i can create, otherwise it will have to be multiple transmissions post. 

Thanks for the help @aydrian

**Comment by aydrian** [comment]
No worries. There's no reason to squish everything into one post if it doesn't make sense. :)
