### ISSUE TITLE
templates.get broken with v > 2.1.0 

### ISSUE THREAD

**Issue by joelabair** [SparkPost/node-sparkpost#220]
The error returned is 'SyntaxError: Unexpected token u'
When using the callback method.

```javascript
"use strict";

var SparkPost = require('sparkpost');
var client = new SparkPost(); 
client.templates.get('my-id', function(err, res) {
	if (err) {
		console.error(err);
		return process.exit(1);
	} else {
		/* got it - continue */
	}
});
```

**Comment by aydrian** [comment]
Hi. I'm not getting the error. What version of node.js are you using?

**Comment by joelabair** [comment]
v4.8.4

**Comment by aydrian** [comment]
I first ran it with v6.11.2 and it worked. I also ran it with v4.8.4 and it also worked. I am using v2.1.2 of node-sparkpost.

**Comment by joelabair** [comment]
Ok - I'll try to isolate the environment more.

**Comment by aydrian** [comment]
Yeah. Maybe include a stack trace. Just let us know what you figure out.

**Comment by joelabair** [comment]
My Bad.  I was parsing res elsewhere in the code and the key 'body' is undefined.  `JSON.parse(res.body)`  Obviously a change in the 2.1.x series. 

Sorry for the fire alarm.  Thanks for your help.

**Comment by aydrian** [comment]
Glad you were able to track it down. That was a change from 1.x to 2.x, the second argument is the data from the request. So it is res.body.
