### ISSUE TITLE
use substitution_data parameters as string, not number

### ISSUE THREAD

**Issue by mariusa** [SparkPost/node-sparkpost#221]
When passing a substitution_data parameter as number which is over 2147483647, spark puts the number 2147483647 instead of the actual passed value.

Please treat all parameters as string, to avoid this issue.

**Comment by aydrian** [comment]
Hi. This library sends the JSON object unmodified to the SparkPost API. Can you please include an example? Parameters should be passed in the data type you are expecting them in the template. String is not the only data type allowed.

**Comment by mariusa** [comment]
Hi,

email_body is a string as follows 
"https://a.com?id={{id}}"

```

                var message = {
                    transmissionBody: {
                        options: {
                            open_tracking: false,
                            click_tracking: false
                        },
                        content: {
                            from: {
                                email: 'a@a.com',
                                name: 'a'
                            },
                            subject: "subj",
                            text: email_body
                        },

                        recipients: [{
                            address: {
                                email: ...
                            },
                            substitution_data: {
                                id: record_id
                            }
                        }]
                    }
                }
```

record_id is a number over 2b.
using record_id.toString() works. Is this required?

**Comment by aydrian** [comment]
Yes. If you want it to be a string, you'll need to convert it to a string. 
Sometimes I'll do this 
```javascript
record_id+''
```
or if you are using the new es2015 template literals, you can do 
```javascript
`${record_id}`
```
