### ISSUE TITLE
Very old Node.js support

### ISSUE THREAD

**Issue by ewandennis** [SparkPost/node-sparkpost#224]
The README mentions using `node-sparkpost@1.3.8` if you need to support Node.js 0.10. Here's [an SO question](https://stackoverflow.com/questions/46481300/why-dependencies-library-version-is-different-between-package-json-and-npm-info) suggesting that isn't working as expected.

A quick test of `sparkpost@1.3.8` on `Node@0.10.42` shows a few issues:
 - `request ^2.72.0` includes ES2015 syntax which old Node chokes on.
 - Old Node.js needs `--harmony` to enable `const`.

It might be time to revise or remove that README comment. Otherwise, a patch on 1.3.8 might be in order to downgrade some dependencies back into the stone age.

**Comment by aydrian** [comment]
That's very odd as the TravisCI tests always passed when targeting those versions. If someone wants to submit a PR to patch 1.3.8, I wouldn't be opposed, but I leaning toward removing that comment and sticking with supporting the Node LTS.

**Comment by avigoldman** [comment]
Considering we are now on version 10 and version 4 and lower are EOL, I'm also for removing the comment and focusing on active versions.

@ewandennis any opposition to that?

**Comment by jgzamora** [comment]
Removing the comment in #232
