### ISSUE TITLE
 sparkPost go in spam

### ISSUE THREAD

**Issue by ishwardeveloper** [SparkPost/node-sparkpost#228]
Why the email with sparkPost go in spam? while i am using nodemailer to send mail with sparkpost

**Comment by avigoldman** [comment]
Hey @ishwardeveloper 👋

There are a few things you can do you help your emails hit the inbox. Most importantly, make sure you are following best practices. You can follow our [Deliverability Guide](https://www.sparkpost.com/email-deliverability-guide/)
and read the docs on [optimizing deliverability and inbox placement](https://www.sparkpost.com/docs/deliverability/optimizing-deliverability-and-inbox-placement/). I'd also make sure that you have `transactional` set to `true` if you are sending transactional emails (.i.e. password resets, app notifications)

Hopefully, that helps!
