### ISSUE TITLE
No documentation on how to configure for the EU API

### ISSUE THREAD

**Issue by AlexJPotter** [SparkPost/node-sparkpost#234]
In order to get the library working with an EU account it is necessary to set the `origin` via the options parameter, like so:

```javascript
const client = new SparkPost('<YOUR API TOKEN>', { origin: 'https://api.eu.sparkpost.com:443' });
```

The fact that you need to do this is not documented anywhere in the README.

If you fail to set the origin you just get a cryptic 401 Unauthorized error every time you make a request as the request is going to the US API - from this it is incredibly hard to figure out what you're doing wrong.

I propose that we add to the documentation to inform EU users that they need to pass a different origin when initialising a client in order to point at the EU API.

**Comment by jgzamora** [comment]
Thanks for reporting and fixing @AlexJPotter , I merged your PR.
