### ISSUE TITLE
Valid API key parameter failing while creating new SparkPost(key) object && Update published NPM module

### ISSUE THREAD

**Issue by bdeanindy** [SparkPost/node-sparkpost#36]
## Valid API Key parameter failing while creating new SparkPost client object

The documentation says to supply a string, but the SDK is throwing an error unless you wrap the SparkPost String "key" parameter in an object and give it a single property name "key".

Example for workaround:

```
var SparkPost = require('sparkpost');
var spApiKeyObj = { key: '<yourSparkpostApiKeyHere>'};
var spEmailClient = new SparkPost(spApiKeyObj);
```

Example error code if you follow the documentation and examples (which only pass this in as an unwrapped string):

```
basicExpressApp/node_modules/sparkpost/lib/configuration.js:31
    throw new Error('You must provide an API key');
          ^
Error: You must provide an API key
    at Configuration.setConfig (basicExpressApp/node_modules/sparkpost/lib/configuration.js:31:11)
    at new module.exports (basicExpressApp/node_modules/sparkpost/index.js:8:10)
    at Object.<anonymous> (basicExpressApp/app.js:14:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

## Update published NPM module

Of course, looking deeper at this, I think there could be a mismatch between the published NPM module and the Github master branch source code. Here's why:

* After running ```npm install --save sparkpost``` and setting up as defined above, the error is coming from: node_modules/sparkpost/lib/configuration.js:31:11
* That file does not exist in the current SparkPost master branch code base

**Comment by timnoel1** [comment]
bumped version to 0.1.7 and published

**Comment by aydrian** [comment]
Had to unpublish 0.1.7. Reopening issue.

**Comment by aydrian** [comment]
This is not an issue. It is possible for the master branch to be ahead of the published npm version. To ensure you are using accurate documentation, be sure you are looking at the tagged version that corresponds to package installed from npm.
