### ISSUE TITLE
Accept camelCase or native API format seamlessly

### ISSUE THREAD

**Issue by bdeanindy** [SparkPost/node-sparkpost#45]
We are currently using a toApiFormat method for each of the SDK's resources. This could be abstracted into a pseudo-static class of the SDK which can accept either format elegantly by mapping the request body to match the API standards for both camelCase and the SparkPost API's native format of delimiter separations with underscores "_".

**Comment by max-mathieu** [comment]
> native format of delimiter separations with underscores "_"
also known as snake_case :)

**Comment by bizob2828** [comment]
The reason behind this was not to change from camel to snake but to keep the keys flat. The transmission API has several layers in the object. So html in the sdk is content.html

**Comment by bdeanindy** [comment]
Our SDK should maintain the same request object structures as prescribed in our API documentation (at least for the native API resources) to reduce confusion. If we don't do that, we risk having duplicate documentation which can easily fall out of date.
