### ISSUE TITLE
Non status-code 200 responses in result structure

### ISSUE THREAD

**Issue by tuck1s** [SparkPost/node-sparkpost#51]
With latest node.js API version 0.9.0, the use of the result structure has changed.  Non status-code 200 responses are not being reported back in the 'err' parameter of the callback.
Can you please advise on checks that should be done.  The code examples seem to be insufficient, such as https://github.com/SparkPost/node-sparkpost/blob/master/examples/transmissions/stored_template_send.js

**Comment by aydrian** [comment]
We will be adding this as part of our v1.0.0 release which is targeted for Monday if not sooner.

**Comment by bdeanindy** [comment]
I added a fix in a comment (https://github.com/aydrian/node-sparkpost/commit/e25f50b887cf5389ae65153c2f58a93d7b8d5ea1) with what appears to be a fairly solid fix (might just want to remove the "5" and perhaps the "3" from the selector of the regular expression) relating to this method:

https://github.com/aydrian/node-sparkpost/blob/ISSUE-51/lib/sparkpost.js#L87-L105
