### ISSUE TITLE
Transmissions API Examples are out of date

### ISSUE THREAD

**Issue by jmartin4563** [SparkPost/node-sparkpost#75]
the toApiFormat is flawed, the api requires that the template_id field live inside the content stanza of the post body to send a transmission, but the toApiFormat function does not construct the body in the way it is supposed. It will always result in a HTTP 422 from the API.

**Comment by aydrian** [comment]
The sdk now accepts JSON in the format expected by the API. If you put the template_id in the right place in the JSON object, it should keep it there. Currently the toApiFormat function takes care of converting to the right case.

**Comment by jmartin4563** [comment]
If that's the intended behavior, then I'm going to change this to vet/update the transmissions api examples, because most of them are in the previous style of supplying transmissions information, as opposed to verbatim supplying what the Transmissions API wants

**Comment by jmartin4563** [comment]
Actually apparently this is now a dupe of #76, so I will just close then

**Comment by bdeanindy** [comment]
Sorry...I didn't see you were on this while I was typing. Thanks @jmartin4563

**Comment by jmartin4563** [comment]
'sall good :+1:
