### ISSUE TITLE
Only return res.body

### ISSUE THREAD

**Issue by bdeanindy** [SparkPost/node-sparkpost#81]
We're currently returning the full response which is received from SparkPost, we don't want to do that since consumers of the SDK using this in an web framework like Express.js don't want the headers of the server-side request being transmitted to the client-side code.

**Comment by bdeanindy** [comment]
Updated the labels to get input from other people to find out what is considered "best practice" approach. @bizob2828 @jmartin4563 @richleland  any preferences or thoughts on this?

**Comment by aydrian** [comment]
It appears the Python sdk only returns the body information. One thought would be to return only `data.body` but hang body off that for backwards compatibility. In the future we may want to return models but it would still be nice to provide the original body content.

**Comment by aydrian** [comment]
As a temporary non breaking fix, could we just remove the headers in the `SparkPost.request()` function?

**Comment by jasonrhodes** [comment]
Only truly non-breaking way to give easier access to body would be to maybe do:
```
return callback(null, res, res.body);
```
from the request() method. If you want the body to be the default response, then ultimately it could switch to `return callback(null, res.body, res);` to give access to the full response if you want it, but that's definitely a breaking change. (Breaking changes aren't evil though!)

**Comment by aydrian** [comment]
It's not really about making it easier to get to the body, it's about not returning things we shouldn't.

**Comment by aydrian** [comment]
We will look at this issue again as we get closer to the next major release. We aren't exposing anything to the caller that they don't already have. People using Express.js will probably simplify or manipulate the results before passing to the client side.

**Comment by aydrian** [comment]
Look into allowing a debug flag on the options that will hang the full res on a debug prop only when the flag is true.

**Comment by aydrian** [comment]
To follow the standard used in other libaries, if `res.body.results` exists, we will return it, else we will return `res.body`.
