### ISSUE TITLE
Docs on Heroku are different than Github's

### ISSUE THREAD

**Issue by devanp92** [SparkPost/node-sparkpost#95]
The docs on [Heroku (for Node)](https://devcenter.heroku.com/articles/sparkpost#using-with-node-js) are much different than Github's. For instance, there is no use of [transmissionBody](https://github.com/SparkPost/node-sparkpost/blob/master/examples/transmissions/send_transmission_all_fields.js#L8) or [content](https://github.com/SparkPost/node-sparkpost/blob/master/examples/transmissions/send_transmission_all_fields.js#L42).

I kept receiving this error:

        ERROR:  { [SparkPostError: Unprocessable Entity]
          name: 'SparkPostError',
          errors: 
           [ { message: 'required field is missing',
               description: 'content object or template_id required',
               code: '1400' } ],
          statusCode: 422 }

when using the example in Heroku.

As a side note, Heroku uses camelCase versus Github's snake naming.

**Comment by aydrian** [comment]
Hey, sorry for the confusion. It looks like the example on Heroku is using an older version of the client library. The examples in this repo are correct. And camelCase should work.

**Comment by colestrode** [comment]
I think this has been addressed, can you check when you have a minute @aydrian?

**Comment by richleland** [comment]
Docs were updated on Heroku - closing issue.
